import { promises as fs } from "node:fs";
import path from "node:path";

// Abstraction so a real object store (S3, R2, etc.) can be swapped in
// later without touching call sites — mirrors the EmailProvider pattern
// (see src/lib/email/index.ts). Keys are caller-chosen opaque strings
// (e.g. "documents/<uuid>.pdf"); this interface only handles reading,
// writing, and deleting bytes at a key, not naming policy.
export interface StorageProvider {
  save(key: string, data: Buffer): Promise<void>;
  read(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

// Local disk implementation for this dev build. Files live outside the
// Next.js app directory under /storage/local (gitignored — see
// .gitignore), so they survive a `next build` but aren't committed.
const BASE_DIR = path.join(process.cwd(), "storage", "local");

// Resolves a key to an absolute path AND verifies it can't escape
// BASE_DIR — a key like "../../etc/passwd" must not be readable/writable
// via this provider, even though keys are normally generated by our own
// code (see src/lib/documents/storage-key.ts), not taken directly from
// user input.
function resolveSafePath(key: string): string {
  const resolved = path.join(BASE_DIR, key);
  if (resolved !== BASE_DIR && !resolved.startsWith(BASE_DIR + path.sep)) {
    throw new Error(`Invalid storage key: ${key}`);
  }
  return resolved;
}

class LocalDiskStorageProvider implements StorageProvider {
  async save(key: string, data: Buffer): Promise<void> {
    const filePath = resolveSafePath(key);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, data);
  }

  async read(key: string): Promise<Buffer> {
    return fs.readFile(resolveSafePath(key));
  }

  async delete(key: string): Promise<void> {
    await fs.rm(resolveSafePath(key), { force: true });
  }
}

export const storageProvider: StorageProvider = new LocalDiskStorageProvider();
